apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapi
  template:
    metadata:
      labels:
        app: pythonapi
    spec:
      containers:
      - name: pythonapi
        image: dockerfile:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonapi-service
spec:
  type: NodePort
  selector:
    app: pythonapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001